#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC =
CFLAGS = -Wall
RESINC =
LIBDIR =
LIB = -lSDL2 -lGLEW -lGL
LDFLAGS =

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = priv/dev
DEP_DEBUG =
OUT_DEBUG = priv/dev/fbsim

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = priv/prod
DEP_RELEASE =
OUT_RELEASE = priv/prod/fbsim

OBJ_DEBUG = $(OBJDIR_DEBUG)/texture.o $(OBJDIR_DEBUG)/stb_image.o $(OBJDIR_DEBUG)/shader.o $(OBJDIR_DEBUG)/obj_loader.o $(OBJDIR_DEBUG)/mesh.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/display.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/texture.o $(OBJDIR_RELEASE)/stb_image.o $(OBJDIR_RELEASE)/shader.o $(OBJDIR_RELEASE)/obj_loader.o $(OBJDIR_RELEASE)/mesh.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/display.o

all: debug release

clean: clean_debug clean_release

before_debug:
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug:

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/texture.o: src/texture.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/texture.cpp -o $(OBJDIR_DEBUG)/texture.o

$(OBJDIR_DEBUG)/stb_image.o: src/stb_image.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/stb_image.c -o $(OBJDIR_DEBUG)/stb_image.o

$(OBJDIR_DEBUG)/shader.o: src/shader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/shader.cpp -o $(OBJDIR_DEBUG)/shader.o

$(OBJDIR_DEBUG)/obj_loader.o: src/obj_loader.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/obj_loader.cpp -o $(OBJDIR_DEBUG)/obj_loader.o

$(OBJDIR_DEBUG)/mesh.o: src/mesh.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/mesh.cpp -o $(OBJDIR_DEBUG)/mesh.o

$(OBJDIR_DEBUG)/main.o: src/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/display.o: src/display.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/display.cpp -o $(OBJDIR_DEBUG)/display.o

clean_debug:
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf $(OBJDIR_DEBUG)

before_release:
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release:

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/texture.o: src/texture.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/texture.cpp -o $(OBJDIR_RELEASE)/texture.o

$(OBJDIR_RELEASE)/stb_image.o: src/stb_image.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/stb_image.c -o $(OBJDIR_RELEASE)/stb_image.o

$(OBJDIR_RELEASE)/shader.o: src/shader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/shader.cpp -o $(OBJDIR_RELEASE)/shader.o

$(OBJDIR_RELEASE)/obj_loader.o: src/obj_loader.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/obj_loader.cpp -o $(OBJDIR_RELEASE)/obj_loader.o

$(OBJDIR_RELEASE)/mesh.o: src/mesh.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/mesh.cpp -o $(OBJDIR_RELEASE)/mesh.o

$(OBJDIR_RELEASE)/main.o: src/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/display.o: src/display.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/display.cpp -o $(OBJDIR_RELEASE)/display.o

clean_release:
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release
